In [23]:
import pandas as pd
titanic_data={
              'PassengerId':[1,2,3,4,5],
              'Name':['a','b','c','d','e'],
              'Age':[10,11,12,13,14],
              'Sex':['m','f','m','f','m'],
              'Pclass':[3,1,3,1,3],
              'Survived':[0,1,1,1,0],
              'Fare':[7.25,71.2833,7.925,53.1,8.05],
              'Embarked':['S','C','S','S','S']
              }
df=pd.DataFrame(titanic_data)
df

   PassengerId Name  Age Sex  Pclass  Survived     Fare Embarked
0            1    a   10   m       3         0   7.2500        S
1            2    b   11   f       1         1  71.2833        C
2            3    c   12   m       3         1   7.9250        S
3            4    d   13   f       1         1  53.1000        S
4            5    e   14   m       3         0   8.0500        S

In [16]:
print(df['Sex'].unique())

['m' 'f']

In [20]:
df['Sex']=df['Sex'].map({'m':0,'f':1})
df['Sex'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Sex, dtype: float64

In [28]:
df_encoded=pd.get_dummies(df,columns=['Embarked'],drop_first=True,dtype=int)
print(df_encoded.head())

   PassengerId Name  Age Sex  Pclass  Survived     Fare  Embarked_S
0            1    a   10   m       3         0   7.2500           1
1            2    b   11   f       1         1  71.2833           0
2            3    c   12   m       3         1   7.9250           1
3            4    d   13   f       1         1  53.1000           1
4            5    e   14   m       3         0   8.0500           1

In [29]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
data=pd.DataFrame({'profit':[200,500,1000,1500,3000]})
scaler=MinMaxScaler()
data['profit_nrml']=scaler.fit_transform(data[['profit']])
print(data)

   profit  profit_nrml
0     200     0.000000
1     500     0.107143
2    1000     0.285714
3    1500     0.464286
4    3000     1.000000